### ISSUE TITLE
Token Refresh

### ISSUE THREAD

**Issue by zbindenren** [scottdware/go-bigip#100]
Hi

We created a tool, that polls several Big IP devices with your library. Since this is a long running process, we would need the possibility to refresh the authentication. We use `bigip.NewTokenSession` method to authenticate to the device and the default timeout for the generated token is 1200s.

Would a Pull request be accepted, that implements that functionality.

My plan would be the following:

Modify:
```go
	type authResp struct {
		Token struct {
			Token      string
		}
	}
```

to:
```go
	type authResp struct {
		Token struct {
			Token      string
			Expiration int `json:"expirationMicros"`
			Timeout    int `json:"timeout"`
		}
	}
```

Then create a method:

```go
func (b *BigIP) RefreshTokenSession() error {}
```

Which:
* updates the token timeout with a patch to `fmt.Sprintf("mgmt/shared/authz/tokens/%s", aresp.Token.Token)` if current token is not expired yet
* perform a new login, if token is expired or above patch returns with an error

**Comment by scottdware** [comment]
Hi @zbindenren - I think this would be a good addition. If you want to go ahead and open up a pull request, that would be great. Thank you!

**Comment by zbindenren** [comment]
@scottdware thx. I already have something working. Have to clean up a little. If everything is ok, I will provide a pull request.

**Comment by scottdware** [comment]
I merged your pull request! Thank you for the contribution!

**Comment by zbindenren** [comment]
@scottdware thanks
