### ISSUE TITLE
Adding a monitor to pool deletes all pool settings

### ISSUE THREAD

**Issue by kokhang** [scottdware/go-bigip#13]
When adding a monitor to pool with AddMonitorToPool(), all settings in the pool are removed.

```
f5 := bigip.NewSession("localhost", "admin", "password")
f5.CreatePool("test-pool")
pool, _ := f5.GetPool("test-pool")
pool.AllowSNAT = true
f5.ModifyPool("test-pool", pool)
f5.CreateMonitor("web_http_monitor", "http", 5, 16, "GET /\r\n", "200 OK")
err := f5.AddMonitorToPool("web_http_monitor", "test-pool")
```

After executing this, the value of the allowSNAT flag gets removed.

**Comment by SqiSch** [comment]
Running into the same issue. Thx for the fix.
Please merge the fix #14 or provide another solution @scottdware
