### ISSUE TITLE
Failure to read monitors with tcp parent

### ISSUE THREAD

**Issue by kzittritsch** [scottdware/go-bigip#16]
Given the .tf:

```
provider "bigip" {
  address = "${lookup(var.f5_host,var.domain))}"
  username = "${var.f5_user}"
  password = "${var.f5_pass}"
}

resource "bigip_ltm_monitor" "monitor" {
  name = "/Common/vtdevad-terraformtest-pool-monitor"
  parent = "/Common/tcp"
  timeout = "${var.monitor_timeout}"
  interval = "${var.monitor_interval}"
}
```

It appears that terraform will create the monitor but fail to read it:

```
...
bigip_ltm_monitor.monitor: Creating...
  interval:      "" => "5"
  ip_dscp:       "" => "0"
  manual_resume: "" => "false"
  name:          "" => "/Common/vtdevad-terraformtest-pool-monitor"
  parent:        "" => "/Common/tcp"
  reverse:       "" => "false"
  send:          "" => "GET /\\r\\n"
  time_until_up: "" => "0"
  timeout:       "" => "16"
  transparent:   "" => "false"
Error applying plan:

1 error(s) occurred:

* bigip_ltm_monitor.monitor: Couldn't find monitor %!(EXTRA string=/Common/vtdevad-terraformtest-pool-monitor)

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

I believe the cause of the error is actually occuring in go-bigip at https://github.com/scottdware/go-bigip/blob/master/ltm.go#L981. This only resolves monitors with specific parents - one of which is not `tcp`.

Any idea if there are complications (as in some monitors need specific fields defined that are not included in `bigip_ltm_monitor`) in adding every parent type to the available list in both this provider and go-bigip?

**Comment by kzittritsch** [comment]
On second thought - should I create this in https://github.com/DealerDotCom/terraform-provider-bigip/ instead?

**Comment by Jakauppila** [comment]
This can be closed, the Terraform provider was explicitly validating the parent profiles and was addressed with https://github.com/DealerDotCom/terraform-provider-bigip/pull/5

**Comment by scottdware** [comment]
Closing the issue.
