### ISSUE TITLE
View Pool Member State

### ISSUE THREAD

**Issue by gumper23** [scottdware/go-bigip#18]
Is there a way to view the status of a pool member without changing it? 

I'm trying to write a script that does a failover. My general procedure is:

1. Ensure there are exactly two members in the pool
2. Ensure only one of them is enabled
3. Disable the active member
4. Sync the F5s
5. Enable the previously disabled member
6. Sync the F5s
7. Ensure the end state looks like it should

The problem is, I can't see a way to just view the state of a node using the go-bigip package.

**Comment by scottdware** [comment]
Let me look into that and see if there's a way we can accomplish it.

**Comment by scottdware** [comment]
So, I modified the `PoolMembers` function to return a struct that contains the name and state of each pool member. Iterating over it would provide you a list like so:

```Go
// Assuming you have an established connection already
poolMembers, _ := f5.PoolMembers("some_443_pool")

for _, m := range poolMembers {
    fmt.Printf("%+v\n", m)
}

// output
{Name:x.x.x.x:443 State:down}
{Name:x.x.x.x:443 State:down}
{Name:x.x.x.x:443 State:up}
{Name:x.x.x.x:443 State:up}
```

I haven't committed the changes just yet. Should do them shortly.

**Comment by gumper23** [comment]
@scottdware You rule sir!

**Comment by scottdware** [comment]
Just committed the changes. Thanks for bringing this up, was a nice idea!
