### ISSUE TITLE
Disable escaping of <, >, and & when using json.Marshal

### ISSUE THREAD

**Issue by jakauppila** [scottdware/go-bigip#22]
When configuring a monitor with some special characters, json.Marshal will escape them so it doesn't get submitted to the appliance correctly.

`f5.CreateMonitor("web_http_monitor", "http", 5, 16, "GET /test?x=1&y=2 \r\n", "200 OK")`

**Body before marshal**
`&{web_http_monitor   0 http   5 0 false  200 OK  false GET /test?x=1&y=2 0 16 false 0 }`

**Body after marshal**
`{"name":"web_http_monitor","defaultsFrom":"http","interval":5,"manualResume":"disabled","recv":"200 OK","reverse":"disabled","send":"GET /test?x=1\u0026y=2 \\r\\n","timeout":16,"transparent":"disabled"}`

> String values encode as JSON strings coerced to valid UTF-8, replacing invalid bytes with the Unicode replacement rune. The angle brackets "<" and ">" are escaped to "\u003c" and "\u003e" to keep some browsers from misinterpreting JSON output as HTML. Ampersand "&" is also escaped to "\u0026" for the same reason. This escaping can be disabled using an Encoder that had SetEscapeHTML(false) called on it. 
Source: https://golang.org/pkg/encoding/json/#Marshal

What would be the preferred approach for correcting this?

- Configure a custom Encoder which sets the SetEscapeHTML flag
- The accepted solution in this post just does a replacement after the Marshal with the original value, this was before the above solution was added in Go 1.7: http://stackoverflow.com/questions/28595664/how-to-stop-json-marshal-from-escaping-and

**Comment by Jakauppila** [comment]
@scottdware Any preference on direction for this?

**Comment by baxter19** [comment]
Given that building Terraform requires Go v1.8 (accoring to [https://github.com/hashicorp/terraform](url)) seems like the custom encoder is a better solution?
