### ISSUE TITLE
Move repo to f5devcentral?

### ISSUE THREAD

**Issue by zlesnr** [scottdware/go-bigip#45]
There looks to be diverging code between this repo and the f5devcentral.  Is there interest in moving this code to F5 where there might be more community involvement?

F5devcentral has already forked.  The code in both repos needs improvement to be fully functional.  My team is considering contributing architectural changes to the community, but its unclear where we will get the most support, best review, etc.  Some backwards incompatible changes we're thinking of may alter the architecture slightly in relation to the client and resources.  If there is not interest in our work here, f5devcentral may be a good fit for it.  If neither is a good home for our work, then perhaps yet another fork is in order.

I'd personally like to see one solid code base for this, rather than several semi-complete versions.  What do you think?

**Comment by kenmaglio** [comment]
@zlesnr We found the F5DevCentral code is not complete, and is not really correct Go. It's really python dev's with python standards implementing things how they know .. which doesn't translate to Go well.

We started down the path of creating the GTM stuff ( correctly and working - unlike F5's ) so far. Please take a look at the code base now and see what you think.

Any feedback is welcome!
@scottdware

**Comment by scottdware** [comment]
I agree with having one, standard codebase, no matter where it lies. I am completely fine moving this repo  to F5 DevCentral.
