### ISSUE TITLE
Support for routing bgp instances and neighbours

### ISSUE THREAD

**Issue by stoyanr** [scottdware/go-bigip#81]
We need support for the BGP instance and neighbor iControl REST API endpoints that have been introduced in BIG-IP 13.1, see [Routing commands for BGP and BFD in ZebOS, tmsh, and iControl REST](https://support.f5.com/kb/en-us/products/big-ip_ltm/manuals/product/big-ip-dynamic-routing-with-tmsh-and-icontrol-rest-14-0-0/02.html#guid-78a9a198-982b-4b5f-9b1f-dd267f314bc7).

We can contribute this. Do you accept pull requests for such new features? Do you have any special requirements? I could not find a `CONTRIBUTING` guide.

**Comment by scottdware** [comment]
Hi @stoyanr! I do accept pull requests for new features, as long as it doesn't break what's currently there :) Feel free to submit any enhancements you wish, and I'll gladly review and approve them.

I guess I should have a `CONTRIBUTING` guide or something...I'll work on that.

**Comment by scottdware** [comment]
Merged! Thank you for the contributions!

**Comment by stoyanr** [comment]
Unfortunately I noticed an issue and opened another PR for fixing it, #84.
